format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$jobs\
$character"""

add_newline = false

[directory]
truncation_length = 3
truncation_symbol = '../'
read_only = ' 󰌾'

